# Generated by Django 2.2.4 on 2020-04-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0004_auto_20200417_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Img',
            field=models.ImageField(default='123', upload_to='profile_photo'),
        ),
    ]
