# Generated by Django 2.2.4 on 2020-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(help_text='Введи место твоей экскурсии!', max_length=200)),
                ('S_coor', models.FloatField()),
                ('N_coor', models.FloatField()),
                ('Img', models.ImageField(upload_to='')),
                ('Description', models.TextField(help_text='Опиши себя и свою экскурсию!')),
                ('Max_number_of_human', models.SmallIntegerField(help_text='Введи, какое максимальное количество человек может быть на твоей экскурсии')),
                ('Cost', models.SmallIntegerField(help_text='Введи, сколько стоит твоя экскурсия')),
                ('Time', models.SmallIntegerField(help_text='Введи, сколько экскурсия будет длиться')),
                ('Address', models.CharField(help_text='Введи адрес проведения экскурсии', max_length=100)),
                ('City', models.CharField(help_text='Введи город проведения экскурсии', max_length=100)),
            ],
        ),
    ]
