# Generated by Django 2.2.4 on 2020-04-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='Country',
            field=models.CharField(default='Россия', help_text='Введи страну проведения экскурсии', max_length=40),
        ),
        migrations.AddField(
            model_name='excursion',
            name='Short_description',
            field=models.CharField(default='', help_text='Введи короткое описание твоей экскурсии', max_length=60),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='City',
            field=models.CharField(help_text='Введи город проведения экскурсии', max_length=40),
        ),
    ]
