# Generated by Django 2.2.4 on 2020-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20200411_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='Img',
            field=models.ImageField(upload_to='excursion_title'),
        ),
    ]
