# Generated by Django 2.2.4 on 2020-04-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200411_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excursion',
            old_name='Max_number_of_human',
            new_name='Max_number',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='Address',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='N_coor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='S_coor',
            field=models.FloatField(default=0),
        ),
    ]
