# Generated by Django 2.2.4 on 2020-04-17 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
        ('search', '0005_excursion_number_of_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='Made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lk.Profile'),
        ),
    ]
