# Generated by Django 2.2.4 on 2020-04-17 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_auto_20200417_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='Made_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
