# Generated by Django 3.1.6 on 2021-04-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_auto_20200417_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.CharField(help_text='Введи ссылку на твой ВК', max_length=50)),
                ('data', models.DateField(help_text='Выбери удобное для тебя время')),
                ('excursion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='search.excursion')),
            ],
        ),
    ]
